### ISSUE TITLE
Code repo

### ISSUE THREAD

**Issue by 0xmatt1** [BitcoinHEX/contract#23]
I saw it was stated git is not being used mainly, where can we see the source code / what site is it hosted on? Thanks

**Comment by tarmo888** [comment]
Verified source code of the smart-contract is on Etherscan is on https://etherscan.io/address/0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39#code

The UI code for go.hex.win is not public, but anyone can code their own UI or interact with the smart-contract directly from Etherscan
https://etherscan.io/address/0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39#readContract
https://etherscan.io/address/0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39#writeContract

**Comment by 0xmatt1** [comment]
thank you
